# Generated by Django 5.2.5 on 2025-08-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AddField(
            model_name='post',
            name='badge',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='imgLink',
            field=models.TextField(blank=True, null=True),
        ),
    ]
