# Generated by Django 5.2.5 on 2025-08-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rLink',
            field=models.TextField(blank=True, null=True),
        ),
    ]
