# Generated by Django 5.2.5 on 2025-08-18 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_post_rlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rLink',
        ),
    ]
